OrdererOrgs:
  - Name: Orderer
    Domain: cts.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: mojani
    Domain: mojani.cts.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: kaveri
    Domain: kaveri.cts.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: finance
    Domain: finance.cts.com
    Template:
      Count: 1
    Users:
      Count: 1
